// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/HeroSection/Navbar";
// import CallToAction from "@/components/HeroSection/CallToAction";
// import Footer from "@/components/Footer/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Navbar />

//         <main className="pt-28">{children}</main>

//         <CallToAction />
//         <Footer />
//       </body>
//     </html>
//   );
// }



// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }


// export default function AdminLayout({ children }) {
//   return (
//     <div>
//       <main>{children}</main>
//     </div>
//   );
// }


"use client";

import { useState } from "react";
import Sidebar from "@/components/Dashboard/Sidebar";
import Header from "@/components/Dashboard/Haeder";

export default function AdminLayout({ children }) {
  const [activeTab, setActiveTab] = useState("leads");

  return (
    <div className="min-h-screen flex bg-gray-50">
      <Sidebar activeTab={activeTab} setActiveTab={setActiveTab} />

      <main className="flex-1">
        <Header activeTab={activeTab} />
        <div className="p-6">{children}</div>
      </main>
    </div>
  );
}


